export const GET_COURSES_LOADING = 'GET_COURSES_LOADING'
export const GET_COURSES_FAILED = 'GET_COURSES_FAILED'
export const GET_COURSES_SUCCESSFUL = 'GET_COURSES_SUCCESSFUL'

export const LOGIN_USER = 'LOGIN_USER'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT_USER = 'LOGOUT_USER'

export const REGISTER_USER = 'REGISTER_USER'
export const GET_USER_EXPO_TOKEN = 'GET_USER_EXPO_TOKEN'

